# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'petservice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 676)
        MainWindow.setToolTipDuration(1)
        MainWindow.setStyleSheet("background-color: #f9f9fe;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTipDuration(1)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1231, 661))
        self.stackedWidget.setToolTipDuration(1)
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"    background-color:  #525edc;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 14px;\n"
"    border-color: beige;\n"
"    color:#525edc;\n"
"\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AppHistorypage = QtWidgets.QWidget()
        self.AppHistorypage.setToolTipDuration(1)
        self.AppHistorypage.setObjectName("AppHistorypage")
        self.frame_6 = QtWidgets.QFrame(self.AppHistorypage)
        self.frame_6.setGeometry(QtCore.QRect(20, 20, 1201, 621))
        self.frame_6.setToolTipDuration(1)
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color:  #dddff8;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 14px;\n"
"    border-color: beige;\n"
"\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.backPetServiceButton = QtWidgets.QPushButton(self.frame_6)
        self.backPetServiceButton.setGeometry(QtCore.QRect(10, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backPetServiceButton.sizePolicy().hasHeightForWidth())
        self.backPetServiceButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.backPetServiceButton.setFont(font)
        self.backPetServiceButton.setToolTipDuration(1)
        self.backPetServiceButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.backPetServiceButton.setObjectName("backPetServiceButton")
        self.historyTable = QtWidgets.QTableView(self.frame_6)
        self.historyTable.setEnabled(True)
        self.historyTable.setGeometry(QtCore.QRect(10, 100, 1181, 471))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.historyTable.setFont(font)
        self.historyTable.setToolTipDuration(1)
        self.historyTable.setStyleSheet("QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #cce4f5;\n"
"    font: Helvetica;\n"
"    color: #353fb0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ebedfb; /* Background color of selected item */\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #353fb0;\n"
"    font-weight: bold; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: none;\n"
"}\n"
"")
        self.historyTable.setObjectName("historyTable")
        self.label_AppHistory = QtWidgets.QLabel(self.frame_6)
        self.label_AppHistory.setGeometry(QtCore.QRect(20, 60, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_AppHistory.setFont(font)
        self.label_AppHistory.setToolTipDuration(1)
        self.label_AppHistory.setStyleSheet("color: #353fb0")
        self.label_AppHistory.setObjectName("label_AppHistory")
        self.widget = QtWidgets.QWidget(self.frame_6)
        self.widget.setGeometry(QtCore.QRect(760, 70, 431, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.searchInputApp = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchInputApp.setFont(font)
        self.searchInputApp.setToolTipDuration(1)
        self.searchInputApp.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.searchInputApp.setText("")
        self.searchInputApp.setClearButtonEnabled(False)
        self.searchInputApp.setObjectName("searchInputApp")
        self.horizontalLayout_14.addWidget(self.searchInputApp)
        self.searchAppButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.searchAppButton.setFont(font)
        self.searchAppButton.setToolTipDuration(1)
        self.searchAppButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 6em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.searchAppButton.setObjectName("searchAppButton")
        self.horizontalLayout_14.addWidget(self.searchAppButton)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_14)
        self.deleteAppButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteAppButton.sizePolicy().hasHeightForWidth())
        self.deleteAppButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.deleteAppButton.setFont(font)
        self.deleteAppButton.setToolTipDuration(1)
        self.deleteAppButton.setStyleSheet("QPushButton {\n"
"    background-color:  #ec9ea5;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d2202f;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d2202f;\n"
"    border-style: outset;\n"
"}")
        self.deleteAppButton.setObjectName("deleteAppButton")
        self.horizontalLayout_17.addWidget(self.deleteAppButton)
        self.stackedWidget.addWidget(self.AppHistorypage)
        self.page = QtWidgets.QWidget()
        self.page.setToolTipDuration(1)
        self.page.setObjectName("page")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setGeometry(QtCore.QRect(20, 20, 1201, 621))
        self.frame_7.setToolTipDuration(1)
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color:  #dddff8;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 14px;\n"
"    border-color: beige;\n"
"\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.backPetServiceButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.backPetServiceButton_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backPetServiceButton_2.sizePolicy().hasHeightForWidth())
        self.backPetServiceButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.backPetServiceButton_2.setFont(font)
        self.backPetServiceButton_2.setToolTipDuration(1)
        self.backPetServiceButton_2.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.backPetServiceButton_2.setObjectName("backPetServiceButton_2")
        self.serviceTable = QtWidgets.QTableView(self.frame_7)
        self.serviceTable.setEnabled(True)
        self.serviceTable.setGeometry(QtCore.QRect(370, 100, 821, 501))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.serviceTable.setFont(font)
        self.serviceTable.setToolTipDuration(1)
        self.serviceTable.setStyleSheet("QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #cce4f5;\n"
"    font: Helvetica;\n"
"    color: #353fb0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ebedfb; /* Background color of selected item */\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #353fb0;\n"
"    font-weight: bold; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: none;\n"
"}\n"
"")
        self.serviceTable.setObjectName("serviceTable")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(20, 100, 341, 501))
        self.frame_8.setToolTipDuration(1)
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color:  #f9f9fe;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 12px;\n"
"    border-color: beige;\n"
"    padding: 4px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.addServiceButton = QtWidgets.QPushButton(self.frame_8)
        self.addServiceButton.setGeometry(QtCore.QRect(110, 240, 144, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addServiceButton.setFont(font)
        self.addServiceButton.setToolTipDuration(1)
        self.addServiceButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 8em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.addServiceButton.setObjectName("addServiceButton")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.frame_8)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(30, 100, 281, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(36)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_servID = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_servID.setFont(font)
        self.label_servID.setToolTipDuration(1)
        self.label_servID.setStyleSheet("color: #353fb0")
        self.label_servID.setObjectName("label_servID")
        self.horizontalLayout_12.addWidget(self.label_servID)
        self.enterservIDName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterservIDName.setFont(font)
        self.enterservIDName.setToolTipDuration(1)
        self.enterservIDName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterservIDName.setClearButtonEnabled(False)
        self.enterservIDName.setObjectName("enterservIDName")
        self.horizontalLayout_12.addWidget(self.enterservIDName)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.frame_8)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(30, 140, 281, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_Sname = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_Sname.setFont(font)
        self.label_Sname.setToolTipDuration(1)
        self.label_Sname.setStyleSheet("color: #353fb0")
        self.label_Sname.setObjectName("label_Sname")
        self.horizontalLayout_11.addWidget(self.label_Sname)
        self.enterSName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterSName.setFont(font)
        self.enterSName.setToolTipDuration(1)
        self.enterSName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterSName.setClearButtonEnabled(False)
        self.enterSName.setObjectName("enterSName")
        self.horizontalLayout_11.addWidget(self.enterSName)
        self.label_service = QtWidgets.QLabel(self.frame_8)
        self.label_service.setGeometry(QtCore.QRect(110, 40, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_service.setFont(font)
        self.label_service.setToolTipDuration(1)
        self.label_service.setStyleSheet("color: #353fb0")
        self.label_service.setObjectName("label_service")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.frame_8)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(30, 180, 281, 41))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_cost = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_cost.setFont(font)
        self.label_cost.setToolTipDuration(1)
        self.label_cost.setStyleSheet("color: #353fb0")
        self.label_cost.setObjectName("label_cost")
        self.horizontalLayout_13.addWidget(self.label_cost)
        self.enterCost = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterCost.setFont(font)
        self.enterCost.setToolTipDuration(1)
        self.enterCost.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterCost.setReadOnly(False)
        self.enterCost.setClearButtonEnabled(False)
        self.enterCost.setObjectName("enterCost")
        self.horizontalLayout_13.addWidget(self.enterCost)
        self.widget1 = QtWidgets.QWidget(self.frame_7)
        self.widget1.setGeometry(QtCore.QRect(760, 70, 431, 29))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.searchInputService = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchInputService.setFont(font)
        self.searchInputService.setToolTipDuration(1)
        self.searchInputService.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.searchInputService.setText("")
        self.searchInputService.setClearButtonEnabled(False)
        self.searchInputService.setObjectName("searchInputService")
        self.horizontalLayout_15.addWidget(self.searchInputService)
        self.searchServiceButton = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.searchServiceButton.setFont(font)
        self.searchServiceButton.setToolTipDuration(1)
        self.searchServiceButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 6em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.searchServiceButton.setObjectName("searchServiceButton")
        self.horizontalLayout_15.addWidget(self.searchServiceButton)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_15)
        self.deleteServButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteServButton.sizePolicy().hasHeightForWidth())
        self.deleteServButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.deleteServButton.setFont(font)
        self.deleteServButton.setToolTipDuration(1)
        self.deleteServButton.setStyleSheet("QPushButton {\n"
"    background-color:  #ec9ea5;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d2202f;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d2202f;\n"
"    border-style: outset;\n"
"}")
        self.deleteServButton.setObjectName("deleteServButton")
        self.horizontalLayout_18.addWidget(self.deleteServButton)
        self.stackedWidget.addWidget(self.page)
        self.PSSpage = QtWidgets.QWidget()
        self.PSSpage.setToolTipDuration(1)
        self.PSSpage.setObjectName("PSSpage")
        self.pendingTabFrame = QtWidgets.QFrame(self.PSSpage)
        self.pendingTabFrame.setGeometry(QtCore.QRect(780, 40, 441, 611))
        self.pendingTabFrame.setToolTipDuration(1)
        self.pendingTabFrame.setStyleSheet("QFrame {\n"
"    background-color:  #dddff8;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 14px;\n"
"    border-color: beige;\n"
"\n"
"\n"
"}")
        self.pendingTabFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pendingTabFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pendingTabFrame.setObjectName("pendingTabFrame")
        self.label_ownerInfo_3 = QtWidgets.QLabel(self.pendingTabFrame)
        self.label_ownerInfo_3.setGeometry(QtCore.QRect(150, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        self.label_ownerInfo_3.setFont(font)
        self.label_ownerInfo_3.setToolTipDuration(1)
        self.label_ownerInfo_3.setStyleSheet("color: #353fb0")
        self.label_ownerInfo_3.setObjectName("label_ownerInfo_3")
        self.tabWidget = QtWidgets.QTabWidget(self.pendingTabFrame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 421, 561))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border-top: 2px solid #7780e4;\n"
"    background: #a9aeee;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; \n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    width: 187px;\n"
"    min-width: 10ex;\n"
"    padding: 8px;\n"
"    background-color: #7780e4;\n"
"    color: white;\n"
"    font: Bold 14px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 2px solid #7780e4;\n"
"    border-bottom-color: #7780e4;\n"
"    background-color: #7780e4;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 3px;\n"
"    background-color:#a9aeee;\n"
"    margin-background: #dddff8;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #7780e4;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.searchInputPet = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchInputPet.setFont(font)
        self.searchInputPet.setToolTipDuration(1)
        self.searchInputPet.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.searchInputPet.setText("")
        self.searchInputPet.setClearButtonEnabled(False)
        self.searchInputPet.setObjectName("searchInputPet")
        self.horizontalLayout_16.addWidget(self.searchInputPet)
        self.searchPetButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.searchPetButton.setFont(font)
        self.searchPetButton.setToolTipDuration(1)
        self.searchPetButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 5em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.searchPetButton.setObjectName("searchPetButton")
        self.horizontalLayout_16.addWidget(self.searchPetButton)
        self.deletePetButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletePetButton.sizePolicy().hasHeightForWidth())
        self.deletePetButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.deletePetButton.setFont(font)
        self.deletePetButton.setToolTipDuration(1)
        self.deletePetButton.setStyleSheet("QPushButton {\n"
"    background-color:  #ec9ea5;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d2202f;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d2202f;\n"
"    border-style: outset;\n"
"}")
        self.deletePetButton.setObjectName("deletePetButton")
        self.horizontalLayout_16.addWidget(self.deletePetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.petTable = QtWidgets.QTableView(self.tab)
        self.petTable.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.petTable.setFont(font)
        self.petTable.setToolTipDuration(1)
        self.petTable.setStyleSheet("QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #cce4f5;\n"
"    font: Helvetica;\n"
"    color: #353fb0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ebedfb; /* Background color of selected item */\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #353fb0;\n"
"    font-weight: bold; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: none;\n"
"}\n"
"")
        self.petTable.setObjectName("petTable")
        self.verticalLayout_2.addWidget(self.petTable)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.searchInputOwner = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchInputOwner.setFont(font)
        self.searchInputOwner.setToolTipDuration(1)
        self.searchInputOwner.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.searchInputOwner.setText("")
        self.searchInputOwner.setClearButtonEnabled(False)
        self.searchInputOwner.setObjectName("searchInputOwner")
        self.horizontalLayout_10.addWidget(self.searchInputOwner)
        self.searchOwnerButton = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.searchOwnerButton.setFont(font)
        self.searchOwnerButton.setToolTipDuration(1)
        self.searchOwnerButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 5em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.searchOwnerButton.setObjectName("searchOwnerButton")
        self.horizontalLayout_10.addWidget(self.searchOwnerButton)
        self.deleteOwnerButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteOwnerButton.sizePolicy().hasHeightForWidth())
        self.deleteOwnerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.deleteOwnerButton.setFont(font)
        self.deleteOwnerButton.setToolTipDuration(1)
        self.deleteOwnerButton.setStyleSheet("QPushButton {\n"
"    background-color:  #ec9ea5;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 4em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d2202f;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d2202f;\n"
"    border-style: outset;\n"
"}")
        self.deleteOwnerButton.setObjectName("deleteOwnerButton")
        self.horizontalLayout_10.addWidget(self.deleteOwnerButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.ownerTable = QtWidgets.QTableView(self.tab_2)
        self.ownerTable.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.ownerTable.setFont(font)
        self.ownerTable.setToolTipDuration(1)
        self.ownerTable.setStyleSheet("QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #cce4f5;\n"
"    font: Helvetica;\n"
"    color: #353fb0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #ebedfb; /* Background color of selected item */\n"
"\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #353fb0;\n"
"    font-weight: bold; \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #cdd1f5;\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: none;\n"
"}\n"
"")
        self.ownerTable.setObjectName("ownerTable")
        self.verticalLayout_3.addWidget(self.ownerTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.historyButton = QtWidgets.QPushButton(self.PSSpage)
        self.historyButton.setGeometry(QtCore.QRect(590, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.historyButton.setFont(font)
        self.historyButton.setToolTipDuration(1)
        self.historyButton.setStyleSheet("QPushButton {\n"
"    background-color: #929ae9;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 8em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.historyButton.setObjectName("historyButton")
        self.label_StudentInformation = QtWidgets.QLabel(self.PSSpage)
        self.label_StudentInformation.setGeometry(QtCore.QRect(30, 80, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_StudentInformation.setFont(font)
        self.label_StudentInformation.setToolTipDuration(1)
        self.label_StudentInformation.setStyleSheet("color: #353fb0")
        self.label_StudentInformation.setObjectName("label_StudentInformation")
        self.infoFrame = QtWidgets.QFrame(self.PSSpage)
        self.infoFrame.setGeometry(QtCore.QRect(20, 130, 751, 491))
        self.infoFrame.setToolTipDuration(1)
        self.infoFrame.setStyleSheet("QFrame {\n"
"    background-color:  #dddff8;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 14px;\n"
"    border-color: beige;\n"
"\n"
"\n"
"}")
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.frame = QtWidgets.QFrame(self.infoFrame)
        self.frame.setGeometry(QtCore.QRect(20, 30, 351, 201))
        self.frame.setToolTipDuration(1)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color:  #f9f9fe;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 12px;\n"
"    border-color: beige;\n"
"    padding: 4px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(36)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Pname = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_Pname.setFont(font)
        self.label_Pname.setToolTipDuration(1)
        self.label_Pname.setStyleSheet("color: #353fb0")
        self.label_Pname.setObjectName("label_Pname")
        self.horizontalLayout.addWidget(self.label_Pname)
        self.enterPName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterPName.setFont(font)
        self.enterPName.setToolTipDuration(1)
        self.enterPName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterPName.setClearButtonEnabled(False)
        self.enterPName.setObjectName("enterPName")
        self.horizontalLayout.addWidget(self.enterPName)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 100, 301, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_species = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_species.setFont(font)
        self.label_species.setToolTipDuration(1)
        self.label_species.setStyleSheet("color: #353fb0")
        self.label_species.setObjectName("label_species")
        self.horizontalLayout_3.addWidget(self.label_species)
        self.enterSpecies = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterSpecies.setFont(font)
        self.enterSpecies.setToolTipDuration(1)
        self.enterSpecies.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterSpecies.setClearButtonEnabled(False)
        self.enterSpecies.setObjectName("enterSpecies")
        self.horizontalLayout_3.addWidget(self.enterSpecies)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 140, 301, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(35)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_breed = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_breed.setFont(font)
        self.label_breed.setToolTipDuration(1)
        self.label_breed.setStyleSheet("color: #353fb0\n"
"")
        self.label_breed.setObjectName("label_breed")
        self.horizontalLayout_4.addWidget(self.label_breed)
        self.enterBreed = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterBreed.setFont(font)
        self.enterBreed.setToolTipDuration(1)
        self.enterBreed.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterBreed.setClearButtonEnabled(False)
        self.enterBreed.setObjectName("enterBreed")
        self.horizontalLayout_4.addWidget(self.enterBreed)
        self.label_petInfo = QtWidgets.QLabel(self.frame)
        self.label_petInfo.setGeometry(QtCore.QRect(10, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        self.label_petInfo.setFont(font)
        self.label_petInfo.setToolTipDuration(1)
        self.label_petInfo.setStyleSheet("color: #353fb0")
        self.label_petInfo.setObjectName("label_petInfo")
        self.frame_2 = QtWidgets.QFrame(self.infoFrame)
        self.frame_2.setGeometry(QtCore.QRect(390, 30, 341, 201))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color:  #f9f9fe;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 12px;\n"
"    border-color: beige;\n"
"    padding: 4px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_ownerInfo = QtWidgets.QLabel(self.frame_2)
        self.label_ownerInfo.setGeometry(QtCore.QRect(10, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        self.label_ownerInfo.setFont(font)
        self.label_ownerInfo.setToolTip("")
        self.label_ownerInfo.setToolTipDuration(1)
        self.label_ownerInfo.setStyleSheet("color: #353fb0")
        self.label_ownerInfo.setObjectName("label_ownerInfo")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 301, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(36)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Pname_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_Pname_2.setFont(font)
        self.label_Pname_2.setToolTipDuration(1)
        self.label_Pname_2.setStyleSheet("color: #353fb0")
        self.label_Pname_2.setObjectName("label_Pname_2")
        self.horizontalLayout_2.addWidget(self.label_Pname_2)
        self.enterOName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterOName.setFont(font)
        self.enterOName.setToolTipDuration(1)
        self.enterOName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterOName.setClearButtonEnabled(False)
        self.enterOName.setObjectName("enterOName")
        self.horizontalLayout_2.addWidget(self.enterOName)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 110, 301, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Pname_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_Pname_3.setFont(font)
        self.label_Pname_3.setToolTipDuration(1)
        self.label_Pname_3.setStyleSheet("color: #353fb0")
        self.label_Pname_3.setObjectName("label_Pname_3")
        self.horizontalLayout_5.addWidget(self.label_Pname_3)
        self.enterOName_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enterOName_2.setFont(font)
        self.enterOName_2.setToolTipDuration(1)
        self.enterOName_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"")
        self.enterOName_2.setClearButtonEnabled(False)
        self.enterOName_2.setObjectName("enterOName_2")
        self.horizontalLayout_5.addWidget(self.enterOName_2)
        self.frame_5 = QtWidgets.QFrame(self.infoFrame)
        self.frame_5.setGeometry(QtCore.QRect(20, 250, 711, 151))
        self.frame_5.setToolTipDuration(1)
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color:  #f9f9fe;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 12px;\n"
"    border-color: beige;\n"
"    padding: 4px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 50, 174, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_date = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_date.setFont(font)
        self.label_date.setToolTipDuration(1)
        self.label_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_date.setStyleSheet("color: #353fb0")
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_6.addWidget(self.label_date)
        self.dateEdit = QtWidgets.QDateEdit(self.horizontalLayoutWidget_6)
        self.dateEdit.setToolTipDuration(1)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #dddff8;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #f6faff,\n"
"                                stop:1 #e9f1fe);\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(path/to/down_arrow_icon.png); #need change\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 90, 171, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_date_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_date_2.setFont(font)
        self.label_date_2.setToolTipDuration(1)
        self.label_date_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_date_2.setStyleSheet("color: #353fb0")
        self.label_date_2.setObjectName("label_date_2")
        self.horizontalLayout_7.addWidget(self.label_date_2)
        self.timeEdit = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_7)
        self.timeEdit.setToolTipDuration(1)
        self.timeEdit.setStyleSheet("QTimeEdit {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: white;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"}\n"
"\n"
"QTimeEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #dddff8;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #f6faff,\n"
"                                stop:1 #e9f1fe);\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow {\n"
"    image: url(path/to/down_arrow_icon.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow:hover {\n"
"    image: url(path/to/down_arrow_icon_hover.png);\n"
"}")
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_7.addWidget(self.timeEdit)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(210, 50, 261, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_availType = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_availType.setFont(font)
        self.label_availType.setToolTipDuration(1)
        self.label_availType.setStyleSheet("color: #353fb0")
        self.label_availType.setObjectName("label_availType")
        self.horizontalLayout_8.addWidget(self.label_availType)
        self.chooseAvailType = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.chooseAvailType.setFont(font)
        self.chooseAvailType.setToolTipDuration(1)
        self.chooseAvailType.setStyleSheet("QComboBox {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: #ebedfb;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"    font: Helvetica;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    border-left-width: 0px;\n"
"    border-left-color: #dddff8;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #ebedfb;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/Documents/codes/python/Pet Service/CCC151-Pet-Service-System/down-arrow.png);\n"
"    width: 15px;  \n"
"    height: 15px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: #ebedfb;\n"
"    color:  #353fb0;\n"
"}\n"
"\n"
"")
        self.chooseAvailType.setObjectName("chooseAvailType")
        self.chooseAvailType.addItem("")
        self.chooseAvailType.addItem("")
        self.horizontalLayout_8.addWidget(self.chooseAvailType)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(210, 90, 261, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_status = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_status.setFont(font)
        self.label_status.setToolTipDuration(1)
        self.label_status.setStyleSheet("color: #353fb0")
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_9.addWidget(self.label_status)
        self.chooseStatus = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.chooseStatus.setFont(font)
        self.chooseStatus.setToolTipDuration(1)
        self.chooseStatus.setStyleSheet("QComboBox {\n"
"    border: 1px solid #dddff8;\n"
"    border-radius: 6px;\n"
"    padding: 2px 10px;\n"
"    background-color: #ebedfb;\n"
"    font: 14px;\n"
"    color: #353fb0;\n"
"    font: Helvetica;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    border-left-width: 0px;\n"
"    border-left-color: #dddff8;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #ebedfb;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(D:/Documents/codes/python/Pet Service/CCC151-Pet-Service-System/down-arrow.png);\n"
"    width: 15px;  \n"
"    height: 15px;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    background-color: #ebedfb;\n"
"    color:  #353fb0;\n"
"}\n"
"\n"
"")
        self.chooseStatus.setObjectName("chooseStatus")
        self.chooseStatus.addItem("")
        self.chooseStatus.addItem("")
        self.horizontalLayout_9.addWidget(self.chooseStatus)
        self.horizontalLayout_9.setStretch(1, 1)
        self.label_appDetails = QtWidgets.QLabel(self.frame_5)
        self.label_appDetails.setGeometry(QtCore.QRect(10, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        self.label_appDetails.setFont(font)
        self.label_appDetails.setToolTipDuration(1)
        self.label_appDetails.setStyleSheet("color: #353fb0")
        self.label_appDetails.setObjectName("label_appDetails")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(480, 10, 221, 121))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_course_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_course_3.setFont(font)
        self.label_course_3.setToolTipDuration(1)
        self.label_course_3.setStyleSheet("color: #353fb0")
        self.label_course_3.setObjectName("label_course_3")
        self.verticalLayout.addWidget(self.label_course_3)
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_10)
        self.listWidget.setToolTipDuration(1)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #dddff8;\n"
"    font: Helvetica;\n"
"    color: #353fb0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color:  #ebedfb; /* Background color of selected item */\n"
"    color: #353fb0;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #dddff8; /* Background color on hover */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #dddff8;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:  #ebedfb;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #dddff8;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color:  #ebedfb;\n"
"    height: 12px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #cdd1f5;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #b5d8f0;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background-color: none;\n"
"}\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.addAppButton = QtWidgets.QPushButton(self.infoFrame)
        self.addAppButton.setGeometry(QtCore.QRect(290, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addAppButton.setFont(font)
        self.addAppButton.setToolTipDuration(1)
        self.addAppButton.setStyleSheet("QPushButton {\n"
"    background-color:  #7780e4;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 8em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.addAppButton.setObjectName("addAppButton")
        self.ServicesButton = QtWidgets.QPushButton(self.PSSpage)
        self.ServicesButton.setGeometry(QtCore.QRect(410, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ServicesButton.setFont(font)
        self.ServicesButton.setToolTipDuration(1)
        self.ServicesButton.setStyleSheet("QPushButton {\n"
"    background-color: #929ae9;\n"
"    border-style: outset;\n"
"    border-width: 0px;\n"
"    border-radius: 8px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    color: white;\n"
"    min-width: 8em;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #525edc;\n"
"    border-style: inset;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #525edc;\n"
"    border-style: outset;\n"
"}")
        self.ServicesButton.setObjectName("ServicesButton")
        self.stackedWidget.addWidget(self.PSSpage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setToolTipDuration(1)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        self.historyButton.clicked.connect(self.stackedWidget.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backPetServiceButton.setText(_translate("MainWindow", "Back"))
        self.label_AppHistory.setText(_translate("MainWindow", "Appointment History"))
        self.searchInputApp.setPlaceholderText(_translate("MainWindow", "  Search appointment..."))
        self.searchAppButton.setText(_translate("MainWindow", "Search"))
        self.deleteAppButton.setText(_translate("MainWindow", "Delete"))
        self.backPetServiceButton_2.setText(_translate("MainWindow", "Back"))
        self.addServiceButton.setText(_translate("MainWindow", "Add Service"))
        self.label_servID.setText(_translate("MainWindow", "ID:"))
        self.enterservIDName.setPlaceholderText(_translate("MainWindow", "  Enter service ID"))
        self.label_Sname.setText(_translate("MainWindow", "Name:"))
        self.enterSName.setPlaceholderText(_translate("MainWindow", "  Enter name of service"))
        self.label_service.setText(_translate("MainWindow", "Services"))
        self.label_cost.setText(_translate("MainWindow", "Cost:"))
        self.enterCost.setPlaceholderText(_translate("MainWindow", "  Enter cost of service"))
        self.searchInputService.setPlaceholderText(_translate("MainWindow", "  Search service..."))
        self.searchServiceButton.setText(_translate("MainWindow", "Search"))
        self.deleteServButton.setText(_translate("MainWindow", "Delete"))
        self.label_ownerInfo_3.setText(_translate("MainWindow", "Information Tab"))
        self.searchInputPet.setPlaceholderText(_translate("MainWindow", "  Search pet..."))
        self.searchPetButton.setText(_translate("MainWindow", "Search"))
        self.deletePetButton.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Pet"))
        self.searchInputOwner.setPlaceholderText(_translate("MainWindow", "  Search owner..."))
        self.searchOwnerButton.setText(_translate("MainWindow", "Search"))
        self.deleteOwnerButton.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", " Owner"))
        self.historyButton.setText(_translate("MainWindow", "History"))
        self.label_StudentInformation.setText(_translate("MainWindow", "Pet Service System"))
        self.label_Pname.setText(_translate("MainWindow", "Name:"))
        self.enterPName.setPlaceholderText(_translate("MainWindow", "  Enter name of pet"))
        self.label_species.setText(_translate("MainWindow", "Species:"))
        self.enterSpecies.setPlaceholderText(_translate("MainWindow", "  Enter species of pet"))
        self.label_breed.setText(_translate("MainWindow", "Breed:"))
        self.enterBreed.setPlaceholderText(_translate("MainWindow", "  Enter species of pet"))
        self.label_petInfo.setText(_translate("MainWindow", "Pet Information"))
        self.label_ownerInfo.setText(_translate("MainWindow", "Owner Information"))
        self.label_Pname_2.setText(_translate("MainWindow", "Name:"))
        self.enterOName.setPlaceholderText(_translate("MainWindow", "  Enter name of owner"))
        self.label_Pname_3.setText(_translate("MainWindow", "Phone Number:"))
        self.enterOName_2.setPlaceholderText(_translate("MainWindow", "  Enter phone number"))
        self.label_date.setText(_translate("MainWindow", "Date:"))
        self.label_date_2.setText(_translate("MainWindow", "Time:"))
        self.label_availType.setText(_translate("MainWindow", "Avail Type:"))
        self.chooseAvailType.setCurrentText(_translate("MainWindow", "rwe"))
        self.chooseAvailType.setItemText(0, _translate("MainWindow", "rwe"))
        self.chooseAvailType.setItemText(1, _translate("MainWindow", "fewf"))
        self.label_status.setText(_translate("MainWindow", "Status:"))
        self.chooseStatus.setCurrentText(_translate("MainWindow", "rwe"))
        self.chooseStatus.setItemText(0, _translate("MainWindow", "rwe"))
        self.chooseStatus.setItemText(1, _translate("MainWindow", "fewf"))
        self.label_appDetails.setText(_translate("MainWindow", "Appointment Details"))
        self.label_course_3.setText(_translate("MainWindow", "Avail Service:"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "a"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "d"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "s"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "d"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "f"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.addAppButton.setText(_translate("MainWindow", "Add Appointment"))
        self.ServicesButton.setText(_translate("MainWindow", "Services"))
